# What programming language is this code written in
language: python

# List of operating systems to test on
# Since this runs on an Ubuntu Server VM, I only care about testing Linux
os: linux

# List of all of the different version of Python to test on
# If all these pass, then you can run this project with any of these Python versions
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

# Install any dependencies needed
install:
  - pip install -r backend/requirements.txt

# The test script for Travis CI to run
# If this exits with a non-zero return code, then the build is considered "failed"
script:
  - python backend/tests/first.py
